export const plans = [
    {
      title: "Trail",
      products: 15,
      images: 20,
      categories: 5,
      brands: 5,
      poster: 1,
      user: 1,
      aboutPage: false,
      variant: false,
      subVariant: false,
      multiUnit: false,
      productFeedback: false,
      warehouseManagement: false,
      paymentIntegration: false,
      sales: false,
      salesOrder: false,
      salesReturn: false,
      purchase: false,
      purchaseReturn: false,
      stockManagement: false,
      salesReport: false,
      purchaseReport: false,
      salesReturnReport: false,
      purchaseReturnReport: false,
      ledgerReport: false,
      productReport: false,
      stockReport: false,
      stockLedgerReport: false,
      trialPeriod: "-",
      oneMonth: "Free",
      sixMonth: "Free",
      twelveMonth: "Free",
    },
    {
      title: "Lite",
      products: 100,
      images: 150,
      categories: 15,
      brands: 15,
      poster: 10,
      user: 1,
      aboutPage: true,
      variant: true,
      subVariant: false,
      multiUnit: false,
      productFeedback: false,
      warehouseManagement: false,
      paymentIntegration: false,
      sales: false,
      salesOrder: false,
      salesReturn: false,
      purchase: false,
      purchaseReturn: false,
      stockManagement: false,
      salesReport: false,
      purchaseReport: false,
      salesReturnReport: false,
      purchaseReturnReport: false,
      ledgerReport: false,
      productReport: false,
      stockReport: false,
      stockLedgerReport: false,
      trialPeriod: 15,
      oneMonth: "₹199",
      sixMonth: "₹1149 (₹191.5/mo)",
      twelveMonth: "₹1999 (₹166.5/mo)",
    },
    {
      title: "Standard",
      products: "Unlimited",
      images: "250MB",
      categories: "Unlimited",
      brands: "Unlimited",
      poster: "Unlimited",
      user: 3,
      aboutPage: true,
      variant: true,
      subVariant: true,
      multiUnit: true,
      productFeedback: true,
      warehouseManagement: true,
      paymentIntegration: false,
      sales: true,
      salesOrder: true,
      salesReturn: false,
      purchase: true,
      purchaseReturn: false,
      stockManagement: true,
      salesReport: true,
      purchaseReport: false,
      salesReturnReport: true,
      purchaseReturnReport: false,
      ledgerReport: true,
      productReport: true,
      stockReport: true,
      stockLedgerReport: false,
      trialPeriod: 10,
      oneMonth: "Coming Soon",
      sixMonth: "Coming Soon",
      twelveMonth: "Coming Soon",
    },
    {
      title: "Profession",
      products: "Unlimited",
      images: "Unlimited",
      categories: "Unlimited",
      brands: "Unlimited",
      poster: "Unlimited",
      user: 5,
      aboutPage: true,
      variant: true,
      subVariant: true,
      multiUnit: true,
      productFeedback: true,
      warehouseManagement: true,
      paymentIntegration: true,
      sales: true,
      salesOrder: true,
      salesReturn: true,
      purchase: true,
      purchaseReturn: true,
      stockManagement: true,
      salesReport: true,
      purchaseReport: true,
      salesReturnReport: true,
      purchaseReturnReport: true,
      ledgerReport: true,
      productReport: true,
      stockReport: true,
      stockLedgerReport: true,
      trialPeriod: 7,
      oneMonth: "Coming Soon",
      sixMonth: "Coming Soon",
      twelveMonth: "Coming Soon",
    },
    {
      title: "Enterprise",
      products: "Unlimited",
      images: "Unlimited",
      categories: "Unlimited",
      brands: "Unlimited",
      poster: "Unlimited",
      user: 10,
      aboutPage: true,
      variant: true,
      subVariant: true,
      multiUnit: true,
      productFeedback: true,
      warehouseManagement: true,
      paymentIntegration: true,
      sales: true,
      salesOrder: true,
      salesReturn: true,
      purchase: true,
      purchaseReturn: true,
      stockManagement: true,
      salesReport: true,
      purchaseReport: true,
      salesReturnReport: true,
      purchaseReturnReport: true,
      ledgerReport: true,
      productReport: true,
      stockReport: true,
      stockLedgerReport: true,
      trialPeriod: "-",
      oneMonth: "Coming Soon",
      sixMonth: "Coming Soon",
      twelveMonth: "Coming Soon",
    },
  ];